# Generated by Django 2.1 on 2018-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0004_auto_20181112_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
